version: '3'
services:
  web:
    container_name: web
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    container_name: redis
    image: "redis:alpine"
